### ISSUE TITLE
In Windows, PopupService.ShowPopupAsync Does Not Show Popup on First Fire

### ISSUE THREAD

**Issue by ennethtpz** [EGoverde/Mvvm.Nucleus.Maui#2]
This is one issue that we are facing in Windows. The first execution of PopupService.ShowPopupAsync does not open an actual popup. When executed again, that's the time when the popup actually shows up.

I actually tried cloning this project and adding it as a project reference to our project to debug this issue, but I couldn't find anything peculiar. I think this could also be an issue with the MAUI Toolkit Popup. I also tried upgrading the MAUI Toolkit to 9.0.1, but it still didn't fix the issue.

**Comment by EGoverde** [comment]
Can you replicate this in the sample project within this repository? I do not have a Windows environment currently to test this. If not, it might have to do with the moment or other specifics when the popup is called.

**Comment by ennethtpz** [comment]
Hi Erik! Sorry for the late reply. Alright let me do this.

I have this hunch that this only happens when you load a popup with a collectionview in it (e.g. dropdowns).

**Comment by ennethtpz** [comment]
Hi @EGoverde,

Upon further investigation, it seems that upgrading the CommunityToolkit.MAUI package from 9.0.0 to 9.0.2 on both here in this library and our project solves this issue. This could be the cause of this issue that was fixed: https://github.com/CommunityToolkit/Maui/pull/1932

However, we are encountering new crashes after updating to 9.0.2 when navigating to certain parts of our app.

I also tried pushing my branch to your repo, but I guess I lack the necessary permissions.

May we request a new version of nucleus that has CommunityToolkit.MAUI 9.0.2, and is optimized for it?

Thanks!
-Enneth

**Comment by EGoverde** [comment]
Hi @turdmaggot. If you add the CommunityToolkit.MAUI package to your project, that version would then be used by Nucleus as well. Generally if you install a dependency manually that is at least the same or higher version no problems should arise from it.

Note that you cannot push branches from your cloned repository directly. Instead you should create a PR from your repository / branch to this one. I can then review and merge it.

**Comment by ennethtpz** [comment]
@EGoverde, thanks for the info! I've already forked this repo instead of just cloning.

FYI, here's where I am so far in this issue:

Seems like the crashing in CommunityToolkit.MAUI 9.0.2 is caused by this one:
https://github.com/CommunityToolkit/Maui/issues/2003

seems like CommunityToolkit.MAUI 9.0.2 has fixed this Windows Popup issue, but has introduced another one! 🙃

The crashing is always triggered by a System.InvalidOperationException: 'Non-nullable are not valid', which was introduced in this commit:
https://github.com/CommunityToolkit/Maui/pull/1926

...and there's an open PR to fix that crashing issue for the upcoming version, and I hope they better make a new release soon:
https://github.com/CommunityToolkit/Maui/pull/2034

I've already tested downgrading CommunityToolkit.MAUI from 8.0.1-7.0.0, and they don't seem to fix the original issue, so I guess we have no choice but to wait this out.

**Comment by EGoverde** [comment]
In my previous comment I did mean forking, rather than cloning. You can PR from your repository to this one. In this case it seems the fix is already merged in the CommunityToolkit.MAUI repository, but there's been no new official release yet.

There is however a nightly feed: https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-MainLatest, which I believe should have the changes you're waiting for already.

If you add any of the Nucleus dependency packages to your project manually, it should use those instead. So you could try using the nightly and see if that fixes your issue.

For now I'll close this issue, as it is an issue in a third-party package.

**Comment by ennethtpz** [comment]
Thanks @EGoverde
